config/routes.rb
class SubdomainConstraint   
  
  def self.matches?(request)     
    request.subdomain.present? && request.subdomain != 'www'   
  end 
end
 
Rails.application.routes.draw do
  constraints SubdomainConstraint do     
    resources "organizations" do
		  member do
		    post :create_user
		    get :new_user
		  end
    end  
  end
  get "home/index"
  root "home#index"
  resources "password_sets", only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
class Organization < ApplicationRecord
  after_create :create_tenant 

  email_regex = /(\A([a-z]*\s*)*\<*([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\>*\Z)/i
  validates :name, length: { maximum: 250 }, presence: true
  validates :email, length: { maximum: 250 }, presence: true, format: { with: email_regex }
  validates :password, length: { maximum: 250 }

  has_many :users, dependent: :destroy

  def create_tenant 
    Apartment::Tenant.create(name) 
  end 
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :organization

  validates :name, :password_digest, length: { maximum: 250 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # around_action :skip_bullet

  protected

  def skip_bullet
    previous_value = Bullet.enable?
    Bullet.enable = false
    yield
  ensure
    Bullet.enable = previous_value
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: :create_user
  def index
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)

    if @organization.save
      OrganizationMailer.with(organization: @organization).welcome_email.deliver_now!
      flash[:notice] = "Email Sent !!!"
      redirect_to new_user_organization_path(id: @organization.id)
    else
      render "new"
    end
  end

  def create_user
    @user = @organization.users.new(user_params)

    if @user.save
      if @organization.users.length == 0
        @user.admin = true
      end
      flash[:notice] = "User created !!!"
      redirect_to root_path
    end
  end

  private

  def organization_params
    params.require(:organizations).permit(:name, :email)
  end

  def user_params
    params.require(:users).permit(:name, :email, :password, :password_confirmation)
  end

  def set_organization
    @organization = Organization.find(params[:id])
  end
end

app/controllers/password_sets_controller.rb
class PasswordSetsController < ApplicationController
  before_action :set_organization
  def edit; end

  def update
    password = params[:password_set][:password]
    password_confirmation = params[:password_set][:password_confirmation]

    if password == password_confirmation && @organization.update(password: password)
      flash[:notice] = "Password Set !!!"
      redirect_to root_path
    else
      render "edit"
    end
  end

  private

  def organization_params
    params.require(:password_set).permit(:password, :password_Confirmation)
  end

  def set_organization
    @organization = Organization.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "PAYROLL"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def flash_message_type(type)
    if type == "notice"
      "success"
    elsif type == "alert"
      "danger"
    else
      type
    end
  end
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= flash_message_type(message_type) %> alert-dismissible fade show flash-message" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav d-flex">
      <li class="nav-item p-2">
        <%= link_to "Payroll", root_path, class: "text-secondary mr-auto" %>
      </li>
      <li class="nav-item p-2">
        <%= link_to "Join Us", new_organization_path, class: "text-secondary" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/organizations/_form.html.erb
<div class="row justify-content-center">
  <div class="col-sm-12 col-md-8">
    <div class="card">
      <div class="card-body">
        <%= form_for :organizations, url: organizations_path, method: :post do |f| %>
          <div class="form-group">
            <%= f.label :name, "Organization Name" %>
            <%= f.text_field :name, class: "form-control", autofocus: true, required: true, placeholder: "Organization Name", maxlength: 100 %>
          </div>

          <div class="form-group">
            <%= f.label :email, "Email address" %>
            <%= f.email_field :email, class: "form-control", autofocus: true, required: true, placeholder: "Email Address", maxlength: 100 %>
          </div>

          </br>

          <%= f.submit class: "btn btn-primary btn-xs-block", data: { disable_with: "Saving..." } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/organizations/new.html.erb
<% provide(:title, "New Organization") %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-12">
      <h3 class="text-center">Create Organization</h3>
    </div>
  </div>

  <%= render "form" %>
</div>

app/views/organizations/new_user.html.erb
<% provide(:title, "New User") %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-12">
      <h3 class="text-center">New User</h3>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-8">
      <div class="card">
        <div class="card-body">
          <%= form_for :users, url: create_user_organization_path, method: :post do |f| %>
            <div class="form-group">
              <%= f.label :name, "Name" %>
              <%= f.text_field :name, class: "form-control", autofocus: true, required: true, placeholder: "Name", maxlength: 100 %>
            </div>

            <div class="form-group">
              <%= f.label :email, "Email" %>
              <%= f.email_field :email, class: "form-control", autofocus: true, required: true, placeholder: "Email", maxlength: 100 %>
            </div>

            <div class="form-group">
              <%= f.label :password, "Password" %>
              <%= f.password_field :password, class: "form-control", autofocus: true, required: true, placeholder: "Password", maxlength: 100 %>
            </div>

            <div class="form-group">
              <%= f.label :password_confirmation, "Password Confirmation" %>
              <%= f.password_field :password_confirmation, class: "form-control", autofocus: true, required: true, placeholder: "Password Confirmation", maxlength: 100 %>
            </div>

            <%= f.submit "Create User", class: "btn btn-primary btn-xs-block", data: { disable_with: "Saving..." } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/password_sets/edit.html.erb
<% provide(:title, "Set Password") %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-12">
      <h3 class="text-center">Create Organization</h3>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-8">
      <div class="card">
        <div class="card-body">
          <%= form_for :password_set, url: password_set_path, method: :put do |f| %>
            <div class="form-group">
              <%= f.label :password, "Password" %>
              <%= f.password_field :password, class: "form-control", autofocus: true, required: true, placeholder: "Email Address", maxlength: 100 %>
            </div>

            <div class="form-group">
              <%= f.label :password_confirmation, "Password Confirmation" %>
              <%= f.password_field :password_confirmation, class: "form-control", autofocus: true, required: true, placeholder: "Password Confirmation", maxlength: 100 %>
            </div>

            <%= f.submit "Set Password", class: "btn btn-primary btn-xs-block", data: { disable_with: "Saving..." } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>